apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  maxReplicas: 8 #PROD# 12
  minReplicas: 4 #PROD# 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend # deployment name
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 200
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 200
