apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: httpgo-hpa
  namespace: http
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpgo-exporter # should match deployment target
  minReplicas: 1
  maxReplicas: 3
  metrics:

  - type: Object
    object:
      metric:
#         name: myapphttp_process_open_fds # name of prometheus metrics to use for hpa
#         name: myapphttp_process_cpu_seconds_total
#         name: myapphttp_established_connections
        name: myapphttp_load1
      describedObject:
        apiVersion: batch/v1
        kind: Job
        name: httpgo-exporter
      target:
        type: Value
        value: 0.25
