kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: cpio1
  namespace: crab
provisioner: kubernetes.io/cinder
parameters:
  type: cpio1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-claim0
  name: postgres-claim0
  namespace: redash
  annotations:
    volume.beta.kubernetes.io/storage-class: cpio1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
