kind: Service
apiVersion: v1
metadata:
  name: dbs-phys03-r
  namespace: dbs
spec:
  selector:
    app: dbs-phys03-r
  ports:
    - port: 8254
      targetPort: 8254
      name: dbs-phys03-r
    - port: 18254
      targetPort: 18254
      name: dbs-pr-mon
    - port: 19254
      targetPort: 19254
      name: dbs-pr-cpy-mon
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dbs-phys03-r
  labels:
    app: dbs-phys03-r
  namespace: dbs
data:
  setup-certs-and-run.sh: |
    #!/bin/bash

    cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    su  -c "cd /data && /data/run.sh" --preserve-environment _dbs
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dbs-phys03-r
  name: dbs-phys03-r
  namespace: dbs
spec:
  selector:
    matchLabels:
      app: dbs-phys03-r
  replicas: 1 #PROD# 5
  template:
    metadata:
      labels:
        app: dbs-phys03-r
        env: k8s #k8s#
        job: dbs-phys03-r
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "18254"
#         prometheus.io/port: "19254"
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: cmssw/dbs #imagetag
        name: dbs-phys03-r
        resources:
          requests:
            memory: "2000Mi"
            cpu: "300m"
          limits:
            memory: "10Gi"
            cpu: "2000m"
        ports:
        - containerPort: 8254
          protocol: TCP
          name: dbs-phys03-r
        - containerPort: 18254
          protocol: TCP
          name: dbs-pr-mon
        - containerPort: 19254
          protocol: TCP
          name: dbs-pr-cpy-mon
        command:
        - /bin/bash
        - /opt/setup-certs-and-run/setup-certs-and-run.sh
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - mountPath: /host/etc/grid-security
          name: etc-grid-security
          readOnly: true
        - name: setup-certs-and-run
          mountPath: /opt/setup-certs-and-run
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/dbs
        securityContext:
          privileged: true
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: dbs-phys03-r-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: dbs-phys03-r
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-dbs
