kind: Service
apiVersion: v1
metadata:
  name: dbsmigration
  namespace: dbs
spec:
  selector:
    app: dbsmigration
  ports:
    - port: 8251
      targetPort: 8251
      name: dbsmigration
    - port: 18251
      targetPort: 18251
      name: dbsmig-mon
    - port: 19251
      targetPort: 19251
      name: dbsmig-cpy-mon
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dbsmigration
  labels:
    app: dbsmigration
  namespace: dbs
data:
  setup-certs-and-run.sh: |
    #!/bin/bash
    cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    su  -c "cd /data && /data/run.sh" --preserve-environment _dbsmigration
---    
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dbsmigration
  name: dbsmigration
  namespace: dbs
spec:
  selector:
    matchLabels:
      app: dbsmigration
  replicas: 1 #PROD# 5
  template:
    metadata:
      labels:
        app: dbsmigration
        env: k8s #k8s#
        job: dbsmigration
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "18251"
#         prometheus.io/port: "19251"
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: cmssw/dbsmigration #imagetag
        name: dbsmigration
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "10Gi"
            cpu: "800m"
        ports:
        - containerPort: 8251
          protocol: TCP
          name: dbsmigration
        - containerPort: 18251
          protocol: TCP
          name: dbsmig-mon
        - containerPort: 19251
          protocol: TCP
          name: dbsmig-cpy-mon
        command:
        - /bin/bash
        - /opt/setup-certs-and-run/setup-certs-and-run.sh
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - mountPath: /host/etc/grid-security
          name: etc-grid-security
          readOnly: true
        - name: setup-certs-and-run
          mountPath: /opt/setup-certs-and-run
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/dbsmigration
        securityContext:
          privileged: true
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: dbsmigration-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: dbsmigration
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-dbs
