kind: Service
apiVersion: v1
metadata:
  name: ms-monitor
  namespace: dmwm
spec:
  selector:
    app: ms-monitor
  ports:
    - port: 8248
      targetPort: 8248
      name: ms-monitor
    - port: 18248
      targetPort: 18248
      name: ms-monitor-mon
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ms-monitor
  labels:
    app: ms-monitor
  namespace: dmwm
data:
  setup-certs-and-run.sh: |
    #!/bin/bash
    cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    su  -c "cd /data && /data/run.sh" --preserve-environment _reqmgr2ms
---    
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: ms-monitor
  name: ms-monitor
  namespace: dmwm
spec:
  selector:
    matchLabels:
      app: ms-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-monitor
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "18248"
    spec:
      # use hostNetwork to allow communication between reqmgr2ms/reqmon/workqueue and couch
#       hostNetwork: true
#       dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: cmssw/reqmgr2ms #imagetag
        name: ms-monitor
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - -c
              - sudo chmod 0777 /data/srv/logs/reqmgr2ms; sudo chown _reqmgr2ms:_reqmgr2ms /data/srv/logs/reqmgr2ms
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8248
          protocol: TCP
          name: ms-monitor
        - containerPort: 18248
          protocol: TCP
          name: ms-monitor-mon
        command:
        - /bin/bash
        - /opt/setup-certs-and-run/setup-certs-and-run.sh
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - mountPath: /host/etc/grid-security
          name: etc-grid-security
          readOnly: true
        - name: setup-certs-and-run
          mountPath: /opt/setup-certs-and-run
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/reqmgr2ms
        securityContext:
          privileged: true
#      initContainers:
#      - name: checkcouchdb
#        image: busybox:1.28
#        command: ['sh', '-c', 'until nslookup couchdb.couchdb; do echo "Waiting for couchdb"; sleep 10; done;']
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: reqmgr2ms-monitor-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: ms-monitor
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-dmwm
